name=FTPSclientOPTA
version=0.3.0
author=dorkmo
maintainer=dorkmo <dorkmo@gmail.com>
sentence=Explicit FTPS client library for Arduino Opta.
paragraph=Provides secure FTP file transfers over Explicit TLS using Mbed networking on Arduino Opta devices.
category=Communication
url=https://github.com/dorkmo/FTPSclientOPTA
architectures=mbed_opta
depends=Ethernet
