name=ArduinoOPTA-FTPS
version=0.0.1
author=dorkmo
maintainer=dorkmo
sentence=Explicit FTPS client library for Arduino Opta.
paragraph=Provides secure FTP file transfers over Explicit TLS using Mbed networking on Arduino Opta devices.
category=Communication
url=https://github.com/dorkmo/ArduinoOPTA-FTPS
architectures=mbed_opta
depends=PortentaEthernet,Ethernet
